# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNModuleTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNModuleTest

  pod 'React', :path => '../node_modules/react-native', :subspecs => ['Dependency']
  pod 'RNWechat', :path => '../node_modules/@yyyyu/react-native-wechat'

end
